all:
	#g++ main.cpp super_ellipse.cpp -o super_ellipse -framework GLUT -framework OpenGL
	g++ main.cpp super_ellipse.cpp controller.cpp viewer.cpp -o model -framework GLUT -framework OpenGL
clean:
	rm *.o model
